# Generated by Django 3.0.5 on 2020-04-26 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('store_name', models.CharField(default='', max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('min_price', models.IntegerField(default=0)),
                ('max_price', models.IntegerField(default=0)),
                ('contact_num', models.CharField(default='', max_length=12)),
                ('country', django_countries.fields.CountryField(default='', max_length=2)),
                ('address', models.CharField(default='', max_length=100)),
                ('time_open', models.TimeField(default=django.utils.timezone.now)),
                ('time_close', models.TimeField(default=django.utils.timezone.now)),
                ('coor_long', models.DecimalField(decimal_places=8, default=124.620937, max_digits=11)),
                ('coor_lat', models.DecimalField(decimal_places=8, default=8.44238, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
